baseurl = 'http://localhost:1313/'
languageCode = 'en'
title = 'Red Rose'
theme = "red-rose"

PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"

pluralizelisttitles = "false"
paginate  = 18
disableHugoGeneratorInject = true

[params]
ava = "/img/mawar.png"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
